ninety9cats/config/routes.rb
Ninety9Cats::Application.routes.draw do
  resources :cats
  resources :cat_rental_requests, only: [:create, :new] do
    member do
      post 'approve'
      post 'deny'
    end
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  root to: "cats#index"
end

ninety9cats/app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = %w(black white orange brown)
  validates :birthdate, :color, :name, :sex, :user_id, presence: true
  validates :color, inclusion: { in: COLORS}
  validates :sex, inclusion: { in: %w( M F )}

  belongs_to :user
  has_many :cat_rental_requests, dependent: :destroy

  def age
    age = Date.today.year - birthdate.year
    age < 1 ? 1 : age
  end
end

ninety9cats/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  STATUS = %w( PENDING DENIED APPROVED )
  validates :cat_id, :start_date, :end_date, :status, :user_id, presence: true
  validates :status, inclusion: { in: STATUS }
  validate :request_already_made_during_dates
  after_initialize :set_to_pending

  belongs_to :cat
  belongs_to :user

  def approve!
    self.status = "APPROVED"
    CatRentalRequest.transaction do
      overlapping_pending_requests.each {|request| request.deny!}
      self.save!
    end
  end

  def deny!
    self.update!(status: "DENIED")
  end

  def pending?
    status == 'PENDING'
  end

  def overlapping_requests
    date_query = "NOT (start_date > ? OR ? > end_date)"
    CatRentalRequest.where(cat_id: cat_id).where(date_query, end_date, start_date)
  end

  def overlapping_pending_requests
    overlapping_requests.where(status: "PENDING")
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: "APPROVED")
  end

  def request_already_made_during_dates
    return if start_date.nil? || end_date.nil?
    if overlapping_approved_requests.count > 0
      errors[:start_date] << "there is a request approved matching those dates"
    end
  end

  def set_to_pending

    self.status ||= 'PENDING'
  end

end

ninety9cats/app/models/user.rb
class User < ActiveRecord::Base
  validates :user_name, :password_digest, :session_token, presence: true
  validates :user_name, uniqueness: true
  after_initialize :ensure_session_token

  attr_reader :password

  has_many :cats
  has_many :cat_rental_requests

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  def generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  private

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

end

ninety9cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  private

  def login_check
    redirect_to root_url if current_user
  end

  def ensure_user_is_owner
    redirect_to root_url unless current_user.id == Cat.find(params[:id]).user_id
  end

end

ninety9cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :ensure_user_is_owner, only: [:approve, :deny]

  def new
    @cat_rental_request = CatRentalRequest.new
    @cats = Cat.all
    render :new
  end

  def create
    @cat_rental_request = CatRentalRequest.new(request_params)
    @cat_rental_request.user_id = current_user.id
    if @cat_rental_request.save
      redirect_to cat_url(request_params[:cat_id])
    else
      @cats = Cat.all
      render :new
    end
  end

  def approve
    @cat_rental_request = CatRentalRequest.find(params[:id])
    @cat_rental_request.approve!
    redirect_to cat_url(@cat_rental_request.cat_id)
  end

  def deny
    @cat_rental_request = CatRentalRequest.find(params[:id])
    @cat_rental_request.deny!
    redirect_to cat_url(@cat_rental_request.cat_id)
  end

  private

  def request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date)
  end
end

ninety9cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :ensure_user_is_owner, only: [:edit, :update]

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :color, :birthdate, :description, :sex)
  end
end

ninety9cats/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :login_check, except: :destroy

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(user_params[:user_name], user_params[:password])
    if @user
      login!(@user)
      redirect_to root_url
    else
      @user = User.new(user_params)
      render :new
    end

  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end

end

ninety9cats/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_check

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to root_url
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

ninety9cats/app/views/cat_rental_requests/new.html.erb
<h1> Submit A Rental Request, Fine Purveyor of Felines </h1>

<form action="<%= cat_rental_requests_url %>" method="post">
  <input
  name="authenticity_token"
  type="hidden"
  value="<%= form_authenticity_token %>">

  <br>

  <label for="cat">Cat Choice:</label>
  <select name="cat_rental_request[cat_id]" id="cat">
    <option value="">SELECT A CAT</option>
    <% @cats.each do |cat| %>
    <option value="<%=cat.id%>" <%= "selected" if cat.id == @cat_rental_request.cat_id%>><%=cat.name.capitalize%></option>
    <% end %>
  </select>

  <br>

  <label for="rental_start_date">Rental Start Date</label>
  <input type="date" name="cat_rental_request[start_date]" id="rental_start_date" value="<%= @cat_rental_request.start_date %>">

  <br>

  <label for="rental_end_date">Rental End Date</label>
  <input type="date" name="cat_rental_request[end_date]" id="rental_end_date" value="<%= @cat_rental_request.end_date %>">

  <br>

  <input type="submit" value=" Maybe Cat ">
</form>

ninety9cats/app/views/cats/_form.html.erb
<% button = ''
    action_url = ''
    hidden = ''
  if cat.persisted?
    button = "Edit"
    action_url = cat_url(cat)
    hidden = "<input type='hidden' name='_method' value='PATCH'>".html_safe
  else
    button = "Create"
    action_url = cats_url
  end
    %>

<form action="<%= action_url %>" method="post">
  <input
  name="authenticity_token"
  type="hidden"
  value="<%= form_authenticity_token %>">
  <%= hidden %>

  <label for="cat_name">Cat's name:</label>
  <input type="text" name="cat[name]" id="cat_name" value="<%=cat.name%>" >

  <br>
  SEX PLEASE
  <input type="radio" name="cat[sex]" id="cat_sex_female" value="F" <%= "checked" if cat.sex == 'F'%>>
  <label for="cat_sex_female">Female</label>

  <input type="radio" name="cat[sex]" id="cat_sex_male" value="M" <%= "checked" if cat.sex == 'M'%>>
  <label for="cat_sex_male">Male</label>

  <br>

  <label for="cat_color">Color:</label>
  <select name="cat[color]" id="cat_color">
    <option value="">SELECT A COLOR</option>
    <% Cat::COLORS.each do |color| %>
    <option value="<%=color%>" <%= "selected" if cat.color == color%>><%=color.capitalize%></option>
    <% end %>
  </select>

  <br>

  <label for="cat_bday">Cat's Berfday</label>
  <input type="date" name="cat[birthdate]" id="cat_bday" value="<%= cat.birthdate %>">

  <br>

  <label for="cat_description">Cat's Life Story</label>
  <textarea name="cat[description]" id="cat_description"><%= cat.description %></textarea>

  <br>

  <input type="submit" value="<%= button %> Cat">
</form>

ninety9cats/app/views/cats/edit.html.erb
<h1> Lets edit the cat </h1>

    <%= render partial: "form", locals: {cat: @cat} %>

ninety9cats/app/views/cats/index.html.erb
<h1> ALL CATS HOMIE! </h1>

  <ul>
    <% @cats.each do |cat| %>
      <li>
        <a href= "<%=cat_url(cat)%>"> <%= cat.name %></a>
      </li>
    <% end %>
  </ul>
  <a href= "<%=new_cat_url%>"> Create Cat or whatever</a>

ninety9cats/app/views/cats/new.html.erb
<h1> Lets make a new cat </h1>


    <%= render partial: "form", locals: {cat: @cat} %>

ninety9cats/app/views/cats/show.html.erb
<h1> <%=@cat.name%>'s Page </h1>

<table>
  <th> Things that define this cat </th>
  <% @cat.attributes.each do |key, val| %>
  <tr>
    <td> <%= key%> </td>
    <td> <%= val%> </td>
  </tr>
  <% end %>

</table>
<br>

<table>
  Requests for <%=@cat.name%>
  <th>Requester Name</th>
  <th>Start Date</th>
  <th>End Date</th>
  <th>Status</th>
  <% @cat.cat_rental_requests.order(:start_date).each do |request| %>
  <tr>
    <td> <%= request.user.user_name %></td>
    <td> <%= request.start_date%> </td>
    <td> <%= request.end_date%> </td>
    <td> <%= request.status%> </td>
    <td> <%= request.pending? ? (button_to "APPROVE!", approve_cat_rental_request_url(request)) : ""%></td>
    <td> <%= request.pending? ? (button_to "D-NIE!", deny_cat_rental_request_url(request)) : ""%></td>
  </tr>
  <% end %>

</table>

<a href="<%= new_cat_rental_request_url%>"> Rent a Cat!</a>
<br>
<a href="<%= edit_cat_url %>">Edit <%= @cat.name%> </a>

ninety9cats/app/views/users/new.html.erb
<h1> Sign Up! </h1>
  <%= render partial: "shared/shared_form", locals: {user: @user, form_case: :sign_up} %>